### ISSUE TITLE
ios 13 deviceToken变化兼容性问题

### ISSUE THREAD

**Issue by xuyuqiang** [v7lin/FakeXinGePush#1]
信鸽推送要升级最新的sdk（iOS SDK v3.3.7），才兼容ios13 devcieToken变化问题

**Comment by v7lin** [comment]
提一个PR吧

**Comment by xuyuqiang** [comment]
已提交，更新了信鸽sdk到v3.3.7

**Comment by xuyuqiang** [comment]
可以更新一下pod上的版本吗？

**Comment by v7lin** [comment]
CI 在执行了 https://travis-ci.org/v7lin/FakeXinGePush

**Comment by xuyuqiang** [comment]
CI是不是执行出问题了？pod上还是没有新版本

**Comment by v7lin** [comment]
是从 fake_push 过来的么，fake_push 已经升级了。不是的话，可以用 QQ_XGPush 替换 FakeXinGePush
